### PR TITLE
Add working redirect from `/awstats`

### PR DESCRIPTION
**Pull request by iliaross**

### CODE REVIEW

**Comment by jcameron** [comment]
Is this going to be compatible with existing domains that use the older redirect? We need to make sure that if AWstats is disabled for them after this patch that the old format redirect will be removed..

Also, isn't this going to break existing links to /awstats/awstats.pl ?

**Comment by iliaross** [comment]
> Is this going to be compatible with existing domains that use the older redirect?

Yes, of course!

> We need to make sure that if AWstats is disabled for them after this patch that the old format redirect will be removed.

Yes, of course! It's already happening.



> Also, isn't this going to break existing links to /awstats/awstats.pl ?

Of course not! :--)

**Comment by jcameron** [comment]
But does the line : 

```
push(@sa, "/awstats $cgidir/awstats.pl");
```

mean that `/awstats` will now map to `awstats.pl` , and so `/awstats/awstats.pl` will map to something like `/awstats.pl/awstats.pl` ?

**Comment by iliaross** [comment]
I don't understand exactly what you're asking, Jamie. But the delete and add rules from this PR, as I tested it are matching both old and new records ..

**Comment by jcameron** [comment]
Ok I see now ... thanks for the patch!

**Pull request merged**
