### PR TITLE
Add arguments option for command line.

### PR DESCRIPTION
**Pull request by manusfreedom**
Add custom arguments for scheduled task of awstats
Add option to generate databases by days (able to request stats for only one day)

### CODE REVIEW

**Comment by jcameron** [comment]
What does this change do overall?

**Comment by manusfreedom** [comment]
I edited first comment.

The database by day is required to use day period:
image

We use it to narrow search (useful to detect mass requests or others), ex:
image

**Comment by iliaross** [comment]
Hello,

Thank you for your patches. Although, this can not be right. See this: https://awstats.sourceforge.io/

**Comment by iliaross** [comment]
Actually, I didn't notice at first that there were other additions and improvements.

On my last comment I was referring to changing the name to `AWstats`. This shouldn't be done.

But I will reopen this so Jamie could comment on the rest of the improvements.

**Comment by jcameron** [comment]
This is a nice patch, but why is it necessary to run the awstats command twice in by-day mode?

**Comment by manusfreedom** [comment]
If I remember correctly, it's because AWStats generates other files for day/time data. According to my old tests, you can't generate them at the same time. https://awstats.sourceforge.io/docs/awstats_faq.html#DAILY

**Comment by jcameron** [comment]
Thanks for the patch!

**Pull request merged**
